##### TensorFlow est une bibliothèque open source de Machine Learning, crée par Google, permettant de développer et d'exécuter des applications de Machine Learning et de Deep Learning.

In [2]:
import tensorflow as tf
tf.__version__

'2.14.0'

### Creer un tenseur

In [5]:
x = tf.constant(3)
print(x)

tf.Tensor(3, shape=(), dtype=int32)


In [6]:
tf.print(x)

3


### Créer un tenseur (shape & type)

In [7]:
x = tf.constant(3, shape=(1,1), dtype=tf.float32)
print(x)

tf.Tensor([[3.]], shape=(1, 1), dtype=float32)


In [8]:
tf.print(x)

[[3]]


### Matrice

In [9]:
M = tf.constant([[2,-1,3],[4,0,2]])
print(M)

tf.Tensor(
[[ 2 -1  3]
 [ 4  0  2]], shape=(2, 3), dtype=int32)


In [10]:
M = tf.constant([[2.,-1,3],[4,0,2]])
print(M)

tf.Tensor(
[[ 2. -1.  3.]
 [ 4.  0.  2.]], shape=(2, 3), dtype=float32)


In [11]:
A = tf.ones((2,3))
print(A)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [12]:
Z = tf.zeros(3)
print(Z)

tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)


In [14]:
B = tf.zeros_like(A)
print(B)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


### Valeurs aléatoires

In [15]:
u = tf.random.normal((4,4), mean=0, stddev=0.6)
print(u)

tf.Tensor(
[[-0.72409505 -0.62467504 -0.48850247  1.1077477 ]
 [-0.60842353 -1.2212702  -0.42766976 -0.44409633]
 [-0.96825117 -0.12351351 -0.3788829  -0.22039405]
 [ 1.5120144  -0.14166811 -0.34845114 -0.27351934]], shape=(4, 4), dtype=float32)


###  range

In [20]:
x = tf.range(10)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


### Cast

In [21]:
x = tf.cast(x, dtype=tf.float32)
print(x)

tf.Tensor([0. 1. 2. 3. 4. 5. 6. 7. 8. 9.], shape=(10,), dtype=float32)
